### ISSUE TITLE
Have to launch from terminal

### ISSUE THREAD

**Issue by ryanleesipes** [evolve-os/quirky#3]
Heard this from other people as well, when installed on Evolve OS, must be launched from terminal.

**Comment by ikeydoherty** [comment]
Must.. ? What happens when launching from the menu? (It works here fwiw.)

**Comment by ryanleesipes** [comment]
Doesn't show up in the menu upon install.

**Comment by ikeydoherty** [comment]
Are you building manually or installing from repo? If its from the repo then it hasn't got the .desktop file. Hasn't been updated yet as changes are active in another branch

**Comment by ryanleesipes** [comment]
From the repo. Makes sense.

On Wed, Jan 14, 2015 at 6:46 PM, Ikey Doherty <notifications@github.com>
wrote:

> Are you building manually or installing from repo? If its from the repo
> then it hasn't got the .desktop file. Hasn't been updated yet as changes
> are active in another branch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evolve-os/quirky/issues/3#issuecomment-70021794>.
>



-- 
Ryan Sipes

**Comment by Justinzobel** [comment]
@ikeydoherty I believe this can be closed for the moment

**Comment by ryanleesipes** [comment]
Yeah, can be closed.
